name: Run tests

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - '*'

jobs:
  built_in_tests:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Install Main Repository as Dependency using Git URL
      run: |
        uv venv
        uv pip install -r requirements.txt
        uv pip install git+https://github.com/rzyu45/SolUtil@master
        uv pip install pytest pytest-xdist pytest-datadir

    - name: Run Tests
      run: |
        uv run pytest
