name: Run tests

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - '*'

jobs:
  built_in_tests:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: |
          uv pip install -e .
          uv pip install git+https://github.com/rzyu45/SolUtil@master
          uv pip install pytest pytest-xdist pytest-datadir

      - name: Run Tests
        run: |
          uv run pytest
